use_frameworks!

target 'BLEManager_Example' do
  pod 'BLEManager', :path => '../'

  target 'BLEManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
